# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 10 22 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install wget
          sudo apt-get -y install curl
      - name: Clone source
        run: |
          cd /home/runner,
          wget https://github.com/okteto/okteto/releases/download/1.8.13/okteto-Linux-x86_64
          chmod +x ./okteto-Linux-x86_64
          sudo mv ./okteto-Linux-x86_64 /usr/bin/okteto
      - name: Go
        run: |
          okteto login --token ${{ secrets.APITOKEN }}
          #okteto的api密钥
          okteto namespace ${{ secrets.namespace }}
          #Namespace用户名
          cd /home/runner/work/okteto-reboot/okteto-reboot
          ls
          # push y
          echo y | okteto push
